CREATE TABLE review_run (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo               VARCHAR(255) NOT NULL,
    base_sha           VARCHAR(64)  NOT NULL,
    head_sha           VARCHAR(64)  NOT NULL,
    prompt_template_id VARCHAR(255),
    status             VARCHAR(32)  NOT NULL,
    created_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    token_input        BIGINT,
    token_output       BIGINT,
    cost_usd           NUMERIC(19, 4)
);

CREATE TABLE generated_test (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_run_id  BIGINT       NOT NULL REFERENCES review_run (id) ON DELETE CASCADE,
    file_path      VARCHAR(512) NOT NULL,
    source         VARCHAR(255) NOT NULL,
    compile_status VARCHAR(32)  NOT NULL,
    pass_status    VARCHAR(32)  NOT NULL
);

CREATE INDEX idx_generated_test_run ON generated_test (review_run_id);

CREATE TABLE review_comment (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_run_id BIGINT       NOT NULL REFERENCES review_run (id) ON DELETE CASCADE,
    file_path     VARCHAR(512) NOT NULL,
    line          INTEGER,
    severity      VARCHAR(32)  NOT NULL,
    category      VARCHAR(32)  NOT NULL,
    body          VARCHAR(8192) NOT NULL,
    human_verdict VARCHAR(32)
);

CREATE INDEX idx_review_comment_run ON review_comment (review_run_id);
