apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: copilotguard
  labels:
    app: copilotguard
spec:
  to:
    kind: Service
    name: copilotguard
  port:
    targetPort: http
  tls:
    termination: edge
